baseURL: "https://adcoop.fr/"
theme: "adcoop"
languageCode: "fr-fr"
enableRobotsTXT: true
enableGitInfo: true

title: "AD COOP | Alban Dericbourg"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "AD COOP"
  description: "Accompagnement de la coopération : facilitation, gouvernance partagée, intelligence collective, conduite du changement, Jeu du Tao — Poitiers (86) / Poitou-Charentes"
  images: 
    - "images/logo.webp"

  logo: "images/logo.webp"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "https://www.facebook.com/adcoop.alban.dericbourg"
    twitter: "#"
    linkedin: "https://www.linkedin.com/company/adcoop/"
    google: "https://maps.app.goo.gl/Rmk4AnKkNMNngq4HA"

  contact:
    - "alban@adcoop.fr"
    - "06 52 93 38 52"

  copyright: "© 2025 Alban Dericbourg"

menus:
  main:
    - name: "Accueil"
      url: "/"
      weight: 1

    - name: "Facilitation"
      url: "/facilitation/"
      weight: 2

    - name: "Jeu du Tao"
      url: "/jeu-du-tao/"
      weight: 3

    - name: "Qui suis-je ?"
      url: "/qui-suis-je/"
      weight: 4

  buttons:
    - name: "Contact"
      url: "/contact/"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Facilitation"
      url: "/facilitation/"
      weight: 1

    - name: "Taoanimation"
      url: "/jeu-du-tao/"
      weight: 2

    - name: "Qui suis-je ?"
      url: "/qui-suis-je/"
      weight: 3

    - name: "Contact"
      url: "/contact/"
      weight: 4

taxonomies: []

frontmatter:
  date:
  - date
  - publishDate
  - lastmod
  expiryDate:
  - expiryDate
  lastmod:
  - :git
  - lastmod
  - date
  - publishDate
  publishDate:
  - publishDate
  - date
